export type GradingAction = 'GRADE_NORMALLY' | 'RESCORE_WITH_SHIFT' | 'AWARD_AUTO_CREDIT'

export interface RescoreEntry {
  q: number       // corrected question number (1-200)
  ans: string     // correct answer
  system: string
  topic: string
  action: GradingAction
  orig: number | null  // original bubble position to read from (null = auto-credit)
}

export const AMBOSS_200Q_MAP: RescoreEntry[] = [
  {q:1,ans:"E",system:"Biochemistry & Genetics",topic:"X-linked recessive inheritance",action:"GRADE_NORMALLY",orig:1},
  {q:2,ans:"B",system:"Biochemistry & Genetics",topic:"Pleiotropy — PKU",action:"GRADE_NORMALLY",orig:2},
  {q:3,ans:"F",system:"Biochemistry & Genetics",topic:"Prader-Willi syndrome — genomic imprinting",action:"GRADE_NORMALLY",orig:3},
  {q:4,ans:"C",system:"Biochemistry & Genetics",topic:"Fragile X — CGG repeat expansion",action:"GRADE_NORMALLY",orig:4},
  {q:5,ans:"E",system:"Biochemistry & Genetics",topic:"Primary ciliary dyskinesia — dynein arm defect",action:"GRADE_NORMALLY",orig:5},
  {q:6,ans:"A",system:"Biochemistry & Genetics",topic:"Trisomy 18 — Edwards syndrome",action:"GRADE_NORMALLY",orig:6},
  {q:7,ans:"B",system:"Biochemistry & Genetics",topic:"Thiamine (B1) deficiency — Wernicke encephalopathy",action:"GRADE_NORMALLY",orig:7},
  {q:8,ans:"A",system:"Biochemistry & Genetics",topic:"Pompe disease — lysosomal acid maltase deficiency",action:"GRADE_NORMALLY",orig:8},
  {q:9,ans:"E",system:"Biochemistry & Genetics",topic:"Carcinoid syndrome — tryptophan hydroxylase",action:"GRADE_NORMALLY",orig:9},
  {q:10,ans:"A",system:"Biochemistry & Genetics",topic:"Fluoroquinolone mechanism — DNA gyrase inhibition",action:"GRADE_NORMALLY",orig:10},
  {q:11,ans:"F",system:"Biochemistry & Genetics",topic:"Gaucher disease — β-glucocerebrosidase deficiency",action:"GRADE_NORMALLY",orig:11},
  {q:12,ans:"E",system:"Biochemistry & Genetics",topic:"Ehlers-Danlos — lysine/hydroxylysine cross-linking defect",action:"GRADE_NORMALLY",orig:12},
  {q:13,ans:"B",system:"Biochemistry & Genetics",topic:"Insulin metabolic effects",action:"GRADE_NORMALLY",orig:13},
  {q:14,ans:"E",system:"Biochemistry & Genetics",topic:"Vitamin B12 — methylmalonyl-CoA mutase cofactor",action:"GRADE_NORMALLY",orig:14},
  {q:15,ans:"A",system:"Biochemistry & Genetics",topic:"Cystic fibrosis — vitamin D deficiency",action:"GRADE_NORMALLY",orig:15},
  {q:16,ans:"G",system:"Biochemistry & Genetics",topic:"Pyridoxine (B6) — aminotransferase cofactor",action:"GRADE_NORMALLY",orig:16},
  {q:17,ans:"B",system:"General Pathology",topic:"Apoptosis — intrinsic pathway",action:"GRADE_NORMALLY",orig:17},
  {q:18,ans:"A",system:"General Pathology",topic:"Coagulative necrosis — splenic infarct",action:"GRADE_NORMALLY",orig:18},
  {q:19,ans:"C",system:"General Pathology",topic:"Methemoglobinemia — dapsone-induced",action:"GRADE_NORMALLY",orig:19},
  {q:20,ans:"F",system:"General Pathology",topic:"Alpha-1-antitrypsin deficiency — LTB4 chemotaxis",action:"GRADE_NORMALLY",orig:20},
  {q:21,ans:"E",system:"General Pathology",topic:"Wound healing — myofibroblasts",action:"GRADE_NORMALLY",orig:21},
  {q:22,ans:"E",system:"General Pathology",topic:"Vascular permeability — endothelial junction separation",action:"GRADE_NORMALLY",orig:22},
  {q:23,ans:"B",system:"General Pathology",topic:"Tuberculosis — Langhans giant cells from macrophages",action:"GRADE_NORMALLY",orig:23},
  {q:24,ans:"D",system:"General Pathology",topic:"IL-2 (aldesleukin) — activates NK cells and cytotoxic T cells",action:"GRADE_NORMALLY",orig:24},
  {q:25,ans:"D",system:"General Pathology",topic:"TNM staging — mediastinal invasion (T4)",action:"GRADE_NORMALLY",orig:25},
  {q:26,ans:"D",system:"General Pathology",topic:"Lynch syndrome — MLH1 mismatch repair mutation",action:"GRADE_NORMALLY",orig:26},
  {q:27,ans:"C",system:"General Pathology",topic:"Li-Fraumeni syndrome — TP53 mutation",action:"GRADE_NORMALLY",orig:27},
  {q:28,ans:"F",system:"General Pathology",topic:"Brain metastases — lung cancer most common source",action:"AWARD_AUTO_CREDIT",orig:null},
  {q:29,ans:"A",system:"General Pathology",topic:"Prostate cancer — PSA, osteoblastic bone metastases",action:"RESCORE_WITH_SHIFT",orig:28},
  {q:30,ans:"A",system:"General Pharmacology",topic:"Urge incontinence — muscarinic M3 antagonism",action:"RESCORE_WITH_SHIFT",orig:29},
  {q:31,ans:"E",system:"General Pharmacology",topic:"Desmopressin — V2 receptor → adenylyl cyclase (Gs)",action:"RESCORE_WITH_SHIFT",orig:30},
  {q:32,ans:"B",system:"General Pharmacology",topic:"Competitive antagonist — rightward shift of dose-response curve",action:"RESCORE_WITH_SHIFT",orig:31},
  {q:33,ans:"B",system:"General Pharmacology",topic:"Enzyme kinetics — increased Vmax, unchanged Km",action:"RESCORE_WITH_SHIFT",orig:32},
  {q:34,ans:"A",system:"General Pharmacology",topic:"High bioavailability — no difference in dose-corrected AUC",action:"RESCORE_WITH_SHIFT",orig:33},
  {q:35,ans:"F",system:"General Pharmacology",topic:"Phase I clinical trial — safety, tolerability, PK/PD",action:"RESCORE_WITH_SHIFT",orig:34},
  {q:36,ans:"F",system:"General Pharmacology",topic:"CYP450 inducer — griseofulvin decreases warfarin levels",action:"RESCORE_WITH_SHIFT",orig:35},
  {q:37,ans:"C",system:"Microbiology",topic:"Chronic granulomatous disease — Serratia (catalase+)",action:"RESCORE_WITH_SHIFT",orig:36},
  {q:38,ans:"E",system:"Microbiology",topic:"CAP — S. pneumoniae polysaccharide capsule",action:"RESCORE_WITH_SHIFT",orig:37},
  {q:39,ans:"E",system:"Microbiology",topic:"Gram-negative sepsis — Lipid A causes hypotension",action:"RESCORE_WITH_SHIFT",orig:38},
  {q:40,ans:"A",system:"Microbiology",topic:"Bordetella pertussis — pertussis toxin increases cAMP",action:"RESCORE_WITH_SHIFT",orig:39},
  {q:41,ans:"D",system:"Microbiology",topic:"Mycoplasma pneumoniae — cold agglutinins, atypical pneumonia",action:"RESCORE_WITH_SHIFT",orig:40},
  {q:42,ans:"F",system:"Microbiology",topic:"Bacillus cereus — preformed emetic toxin, reheated rice",action:"RESCORE_WITH_SHIFT",orig:41},
  {q:43,ans:"A",system:"Microbiology",topic:"Primary syphilis — penicillin inhibits transpeptidase",action:"RESCORE_WITH_SHIFT",orig:42},
  {q:44,ans:"C",system:"Microbiology",topic:"Hepatitis C — needlestick injury, porphyria cutanea tarda",action:"RESCORE_WITH_SHIFT",orig:43},
  {q:45,ans:"B",system:"Microbiology",topic:"HIV entry — CCR5 coreceptor on macrophages",action:"RESCORE_WITH_SHIFT",orig:44},
  {q:46,ans:"D",system:"Microbiology",topic:"HIV prophylaxis — TMP-SMX for PCP (CD4 <200)",action:"RESCORE_WITH_SHIFT",orig:45},
  {q:47,ans:"D",system:"Microbiology",topic:"Zidovudine — NRTI, blocks viral DNA elongation",action:"RESCORE_WITH_SHIFT",orig:46},
  {q:48,ans:"A",system:"Microbiology",topic:"Entamoeba histolytica — trophozoites ingesting RBCs",action:"RESCORE_WITH_SHIFT",orig:47},
  {q:49,ans:"C",system:"Microbiology",topic:"Plasmodium falciparum — RBC inclusion bodies, chloroquine-resistant",action:"RESCORE_WITH_SHIFT",orig:48},
  {q:50,ans:"F",system:"Microbiology",topic:"Cryptococcus neoformans — narrow-necked budding, mucicarmine stain",action:"RESCORE_WITH_SHIFT",orig:49},
  {q:51,ans:"F",system:"Microbiology",topic:"Trichomonas vaginalis — motile flagellated protozoa",action:"RESCORE_WITH_SHIFT",orig:50},
  {q:52,ans:"C",system:"Immune System",topic:"Aging — decreased vaccine responsiveness",action:"RESCORE_WITH_SHIFT",orig:51},
  {q:53,ans:"C",system:"Immune System",topic:"Chronic mucocutaneous candidiasis — T cell defect",action:"RESCORE_WITH_SHIFT",orig:52},
  {q:54,ans:"D",system:"Immune System",topic:"Goodpasture syndrome — type II hypersensitivity",action:"RESCORE_WITH_SHIFT",orig:53},
  {q:55,ans:"C",system:"Immune System",topic:"Acute renal allograft rejection — T cell-mediated allorecognition",action:"RESCORE_WITH_SHIFT",orig:54},
  {q:56,ans:"C",system:"Immune System",topic:"Tetanus vaccine — toxoid (denatured bacterial exotoxin)",action:"RESCORE_WITH_SHIFT",orig:55},
  {q:57,ans:"B",system:"Immune System",topic:"Leukocyte adhesion deficiency — beta-2 integrin (CD18) defect",action:"RESCORE_WITH_SHIFT",orig:56},
  {q:58,ans:"A",system:"Immune System",topic:"Terminal complement deficiency — recurrent Neisseria",action:"RESCORE_WITH_SHIFT",orig:57},
  {q:59,ans:"D",system:"Immune System",topic:"EBV/mononucleosis — risk of Hodgkin lymphoma",action:"RESCORE_WITH_SHIFT",orig:58},
  {q:60,ans:"D",system:"Immune System",topic:"Cyclosporine — calcineurin inhibitor",action:"RESCORE_WITH_SHIFT",orig:59},
  {q:61,ans:"E",system:"Blood & Lymphoreticular System",topic:"Sideroblastic anemia — isoniazid/B6 deficiency",action:"RESCORE_WITH_SHIFT",orig:60},
  {q:62,ans:"C",system:"Blood & Lymphoreticular System",topic:"Lead poisoning — ALA dehydratase inhibition",action:"RESCORE_WITH_SHIFT",orig:61},
  {q:63,ans:"E",system:"Blood & Lymphoreticular System",topic:"Hemolytic disease of newborn — ABO incompatibility",action:"RESCORE_WITH_SHIFT",orig:62},
  {q:64,ans:"C",system:"Blood & Lymphoreticular System",topic:"Alpha-thalassemia minor — cis deletion of alpha-globin genes",action:"RESCORE_WITH_SHIFT",orig:63},
  {q:65,ans:"C",system:"Blood & Lymphoreticular System",topic:"Sickle cell anemia — Howell-Jolly bodies (functional asplenia)",action:"RESCORE_WITH_SHIFT",orig:64},
  {q:66,ans:"E",system:"Blood & Lymphoreticular System",topic:"Polycythemia vera — JAK2 V617F mutation",action:"RESCORE_WITH_SHIFT",orig:65},
  {q:67,ans:"A",system:"Blood & Lymphoreticular System",topic:"AML-M3 — myeloperoxidase, Auer rods, t(15;17)",action:"RESCORE_WITH_SHIFT",orig:66},
  {q:68,ans:"A",system:"Blood & Lymphoreticular System",topic:"Multiple myeloma — osteoclast activating factors",action:"RESCORE_WITH_SHIFT",orig:67},
  {q:69,ans:"A",system:"Blood & Lymphoreticular System",topic:"Hemolytic uremic syndrome — normal PT/PTT, low platelets",action:"RESCORE_WITH_SHIFT",orig:68},
  {q:70,ans:"C",system:"Blood & Lymphoreticular System",topic:"Hemophilia — intrinsic pathway, impaired factor X conversion",action:"RESCORE_WITH_SHIFT",orig:69},
  {q:71,ans:"C",system:"Blood & Lymphoreticular System",topic:"Warfarin — inhibits gamma-carboxylation of glutamate residues",action:"RESCORE_WITH_SHIFT",orig:70},
  {q:72,ans:"F",system:"Blood & Lymphoreticular System",topic:"Anthracyclines — dilated cardiomyopathy",action:"AWARD_AUTO_CREDIT",orig:null},
  {q:73,ans:"D",system:"Blood & Lymphoreticular System",topic:"Testicular cancer — para-aortic lymph node spread",action:"RESCORE_WITH_SHIFT",orig:71},
  {q:74,ans:"E",system:"Cardiovascular System",topic:"Beta-1 antagonism — reduces renin/angiotensin II in CHF",action:"RESCORE_WITH_SHIFT",orig:72},
  {q:75,ans:"C",system:"Cardiovascular System",topic:"Persistent truncus arteriosus — neural crest cell migration failure",action:"RESCORE_WITH_SHIFT",orig:73},
  {q:76,ans:"A",system:"Cardiovascular System",topic:"Tetralogy of Fallot — right axis deviation, boot-shaped heart",action:"RESCORE_WITH_SHIFT",orig:74},
  {q:77,ans:"F",system:"Cardiovascular System",topic:"Cor pulmonale — increased capillary hydrostatic pressure",action:"RESCORE_WITH_SHIFT",orig:75},
  {q:78,ans:"D",system:"Cardiovascular System",topic:"Hypovolemic shock — hemodynamic profile",action:"RESCORE_WITH_SHIFT",orig:76},
  {q:79,ans:"D",system:"Cardiovascular System",topic:"Restrictive cardiomyopathy — cardiac sarcoidosis",action:"RESCORE_WITH_SHIFT",orig:77},
  {q:80,ans:"B",system:"Cardiovascular System",topic:"Mitral stenosis — loud S1 (mitral valve closure)",action:"RESCORE_WITH_SHIFT",orig:78},
  {q:81,ans:"C",system:"Cardiovascular System",topic:"S3 heart sound — increased LV end-systolic volume",action:"RESCORE_WITH_SHIFT",orig:79},
  {q:82,ans:"E",system:"Cardiovascular System",topic:"Dressler syndrome — post-MI autoimmune pericarditis",action:"RESCORE_WITH_SHIFT",orig:80},
  {q:83,ans:"C",system:"Cardiovascular System",topic:"Infective endocarditis — antigen-antibody complex deposition in kidney",action:"RESCORE_WITH_SHIFT",orig:81},
  {q:84,ans:"E",system:"Cardiovascular System",topic:"Wolff-Parkinson-White — delta wave, short PR interval",action:"RESCORE_WITH_SHIFT",orig:82},
  {q:85,ans:"B",system:"Cardiovascular System",topic:"Polyarteritis nodosa — medium-vessel vasculitis, HBV association",action:"RESCORE_WITH_SHIFT",orig:83},
  {q:86,ans:"A",system:"Cardiovascular System",topic:"Familial hyperchylomicronemia — acute pancreatitis risk",action:"RESCORE_WITH_SHIFT",orig:84},
  {q:87,ans:"B",system:"Cardiovascular System",topic:"Statin adverse effects — elevated creatine kinase",action:"RESCORE_WITH_SHIFT",orig:85},
  {q:88,ans:"B",system:"Cardiovascular System",topic:"Superior laryngeal nerve — voice pitch limitation",action:"RESCORE_WITH_SHIFT",orig:86},
  {q:89,ans:"A",system:"Endocrine System",topic:"Graves disease — TSH receptor stimulating autoantibodies",action:"RESCORE_WITH_SHIFT",orig:87},
  {q:90,ans:"B",system:"Endocrine System",topic:"Pregnancy thyroid — increased TBG, normal free T3/T4",action:"RESCORE_WITH_SHIFT",orig:88},
  {q:91,ans:"A",system:"Endocrine System",topic:"Secondary hyperparathyroidism — CKD, rugger-jersey spine",action:"RESCORE_WITH_SHIFT",orig:89},
  {q:92,ans:"B",system:"Endocrine System",topic:"Central diabetes insipidus — posterior pituitary damage",action:"RESCORE_WITH_SHIFT",orig:90},
  {q:93,ans:"A",system:"Endocrine System",topic:"Neuroblastoma — Homer-Wright rosettes, HVA/VMA",action:"RESCORE_WITH_SHIFT",orig:91},
  {q:94,ans:"D",system:"Endocrine System",topic:"Addison disease — primary adrenal insufficiency",action:"RESCORE_WITH_SHIFT",orig:92},
  {q:95,ans:"F",system:"Endocrine System",topic:"Cushing syndrome — ectopic ACTH from small cell lung cancer",action:"RESCORE_WITH_SHIFT",orig:93},
  {q:96,ans:"B",system:"Endocrine System",topic:"Type 2 diabetes — islet amyloid polypeptide accumulation",action:"RESCORE_WITH_SHIFT",orig:94},
  {q:97,ans:"A",system:"Endocrine System",topic:"Glucagonoma — pancreatic alpha-cells, necrolytic migratory erythema",action:"RESCORE_WITH_SHIFT",orig:95},
  {q:98,ans:"F",system:"Endocrine System",topic:"Hemochromatosis — defective HFE/transferrin receptor binding",action:"RESCORE_WITH_SHIFT",orig:96},
  {q:99,ans:"D",system:"Endocrine System",topic:"MEN 2 — RET proto-oncogene gain-of-function mutation",action:"RESCORE_WITH_SHIFT",orig:97},
  {q:100,ans:"A",system:"Endocrine System",topic:"TSH receptor — Gs and Gq coupled (TSH-secreting adenoma)",action:"RESCORE_WITH_SHIFT",orig:98},
  {q:101,ans:"C",system:"Endocrine System",topic:"Sulfonylureas — ATP-sensitive K+ channel blockade",action:"RESCORE_WITH_SHIFT",orig:99},
  {q:102,ans:"B",system:"Endocrine System",topic:"Chagas disease — myenteric plexus destruction",action:"RESCORE_WITH_SHIFT",orig:100},
  {q:103,ans:"D",system:"Gastrointestinal System",topic:"Chagas disease — esophageal dysmotility",action:"RESCORE_WITH_SHIFT",orig:101},
  {q:104,ans:"D",system:"Gastrointestinal System",topic:"Bulimia nervosa — Mallory-Weiss syndrome",action:"RESCORE_WITH_SHIFT",orig:102},
  {q:105,ans:"E",system:"Gastrointestinal System",topic:"PUD — H. pylori strongest risk factor",action:"RESCORE_WITH_SHIFT",orig:103},
  {q:106,ans:"E",system:"Gastrointestinal System",topic:"Whipple disease — Tropheryma whipplei, PAS-positive macrophages",action:"RESCORE_WITH_SHIFT",orig:104},
  {q:107,ans:"G",system:"Gastrointestinal System",topic:"Hirschsprung disease — failure of neural crest cell migration",action:"RESCORE_WITH_SHIFT",orig:105},
  {q:108,ans:"B",system:"Gastrointestinal System",topic:"Crohn disease — Th1/Th17 transmural inflammation",action:"RESCORE_WITH_SHIFT",orig:106},
  {q:109,ans:"D",system:"Gastrointestinal System",topic:"Portal hypertension — superior epigastric vein (caput medusae)",action:"RESCORE_WITH_SHIFT",orig:107},
  {q:110,ans:"E",system:"Gastrointestinal System",topic:"Hepatitis B serology — acute active infection",action:"RESCORE_WITH_SHIFT",orig:108},
  {q:111,ans:"E",system:"Gastrointestinal System",topic:"Acute cholecystitis — cystic duct obstruction",action:"RESCORE_WITH_SHIFT",orig:109},
  {q:112,ans:"E",system:"Gastrointestinal System",topic:"Pancreatic cancer — Courvoisier sign, ionizing radiation",action:"RESCORE_WITH_SHIFT",orig:110},
  {q:113,ans:"C",system:"Skin & Musculoskeletal",topic:"Incus — 1st branchial arch derivative",action:"AWARD_AUTO_CREDIT",orig:null},
  {q:114,ans:"A",system:"Skin & Musculoskeletal",topic:"Congenital rubella — postauricular lymphadenopathy",action:"RESCORE_WITH_SHIFT",orig:111},
  {q:115,ans:"D",system:"Skin & Musculoskeletal",topic:"Tinea versicolor — Malassezia globosa overgrowth",action:"RESCORE_WITH_SHIFT",orig:112},
  {q:116,ans:"E",system:"Skin & Musculoskeletal",topic:"Pemphigus vulgaris — IgG against desmoglein (desmosomes)",action:"RESCORE_WITH_SHIFT",orig:113},
  {q:117,ans:"C",system:"Skin & Musculoskeletal",topic:"NMS — ryanodine receptor, dantrolene treatment",action:"RESCORE_WITH_SHIFT",orig:114},
  {q:118,ans:"C",system:"Skin & Musculoskeletal",topic:"Myasthenia gravis — decreased end plate potential",action:"RESCORE_WITH_SHIFT",orig:115},
  {q:119,ans:"D",system:"Skin & Musculoskeletal",topic:"Serotonin syndrome — sumatriptan + SSRI",action:"RESCORE_WITH_SHIFT",orig:116},
  {q:120,ans:"B",system:"Skin & Musculoskeletal",topic:"Muscle contraction — troponin C binds calcium",action:"RESCORE_WITH_SHIFT",orig:117},
  {q:121,ans:"F",system:"Skin & Musculoskeletal",topic:"SLE — anti-Sm (Smith) antibodies",action:"RESCORE_WITH_SHIFT",orig:118},
  {q:122,ans:"F",system:"Skin & Musculoskeletal",topic:"Limited systemic sclerosis — telangiectasia (CREST)",action:"RESCORE_WITH_SHIFT",orig:119},
  {q:123,ans:"C",system:"Skin & Musculoskeletal",topic:"Rheumatoid arthritis — synovial granulation tissue (pannus)",action:"RESCORE_WITH_SHIFT",orig:120},
  {q:124,ans:"E",system:"Skin & Musculoskeletal",topic:"Reactive arthritis — HLA-B27 positive genotype",action:"RESCORE_WITH_SHIFT",orig:121},
  {q:125,ans:"F",system:"Skin & Musculoskeletal",topic:"Dermatomyositis — ovarian adenocarcinoma association",action:"RESCORE_WITH_SHIFT",orig:122},
  {q:126,ans:"E",system:"Skin & Musculoskeletal",topic:"Paget disease of bone — lamellar interspersed with woven bone",action:"RESCORE_WITH_SHIFT",orig:123},
  {q:127,ans:"A",system:"Skin & Musculoskeletal",topic:"Visual pathway — Meyer loop (temporal lobe, superior field)",action:"RESCORE_WITH_SHIFT",orig:124},
  {q:128,ans:"E",system:"Nervous System & Special Senses",topic:"Horner syndrome — Pancoast tumor, stellate ganglion compression",action:"RESCORE_WITH_SHIFT",orig:125},
  {q:129,ans:"E",system:"Nervous System & Special Senses",topic:"CN III palsy — posterior communicating artery aneurysm",action:"RESCORE_WITH_SHIFT",orig:126},
  {q:130,ans:"C",system:"Nervous System & Special Senses",topic:"Facial nerve (CN VII) — exits at cerebellopontine angle",action:"RESCORE_WITH_SHIFT",orig:127},
  {q:131,ans:"D",system:"Nervous System & Special Senses",topic:"Vitamin B12 — subacute combined degeneration, dorsal columns",action:"RESCORE_WITH_SHIFT",orig:128},
  {q:132,ans:"E",system:"Nervous System & Special Senses",topic:"Huntington disease — caudate nucleus (striatum) atrophy",action:"RESCORE_WITH_SHIFT",orig:129},
  {q:133,ans:"F",system:"Nervous System & Special Senses",topic:"Epidural hematoma — arterial bleeding between dura and skull",action:"RESCORE_WITH_SHIFT",orig:130},
  {q:134,ans:"E",system:"Nervous System & Special Senses",topic:"Left ACA stroke — contralateral leg weakness, transcortical motor aphasia",action:"RESCORE_WITH_SHIFT",orig:131},
  {q:135,ans:"H",system:"Nervous System & Special Senses",topic:"Multiple sclerosis — Th1-mediated demyelination",action:"RESCORE_WITH_SHIFT",orig:132},
  {q:136,ans:"C",system:"Nervous System & Special Senses",topic:"Neurofibromatosis type 2 — chromosome 22, merlin, meningioma",action:"RESCORE_WITH_SHIFT",orig:133},
  {q:137,ans:"C",system:"Nervous System & Special Senses",topic:"Anterior cord syndrome — aortic surgery complication",action:"RESCORE_WITH_SHIFT",orig:134},
  {q:138,ans:"B",system:"Nervous System & Special Senses",topic:"Narcolepsy — decreased orexin-A (hypocretin)",action:"RESCORE_WITH_SHIFT",orig:135},
  {q:139,ans:"E",system:"Nervous System & Special Senses",topic:"Poliomyelitis — anterior horn cell destruction, LMN signs",action:"RESCORE_WITH_SHIFT",orig:136},
  {q:140,ans:"B",system:"Nervous System & Special Senses",topic:"Guillain-Barré syndrome — Schwann cell autoimmune attack",action:"RESCORE_WITH_SHIFT",orig:137},
  {q:141,ans:"C",system:"Nervous System & Special Senses",topic:"Alzheimer disease — extracellular amyloid plaques, trisomy 21",action:"RESCORE_WITH_SHIFT",orig:138},
  {q:142,ans:"G",system:"Nervous System & Special Senses",topic:"Radial nerve palsy — midshaft humerus fracture",action:"RESCORE_WITH_SHIFT",orig:139},
  {q:143,ans:"E",system:"Nervous System & Special Senses",topic:"Organophosphate poisoning — atropine (muscarinic antagonism)",action:"RESCORE_WITH_SHIFT",orig:140},
  {q:144,ans:"E",system:"Nervous System & Special Senses",topic:"Behavioral change stages — contemplation",action:"RESCORE_WITH_SHIFT",orig:141},
  {q:145,ans:"C",system:"Nervous System & Special Senses",topic:"Borderline personality disorder — splitting",action:"RESCORE_WITH_SHIFT",orig:142},
  {q:146,ans:"E",system:"Behavioral Health",topic:"Schizophreniform disorder — 1 to 6 months",action:"RESCORE_WITH_SHIFT",orig:143},
  {q:147,ans:"C",system:"Behavioral Health",topic:"Major depressive disorder — anhedonia ≥2 weeks",action:"RESCORE_WITH_SHIFT",orig:144},
  {q:148,ans:"A",system:"Behavioral Health",topic:"Antisocial personality disorder — conduct disorder + ≥3 adult criteria",action:"RESCORE_WITH_SHIFT",orig:145},
  {q:149,ans:"B",system:"Behavioral Health",topic:"Anorexia nervosa — osteoporosis, stress fractures",action:"RESCORE_WITH_SHIFT",orig:146},
  {q:150,ans:"B",system:"Behavioral Health",topic:"Bipolar disorder — antidepressant monotherapy triggers mania",action:"RESCORE_WITH_SHIFT",orig:147},
  {q:151,ans:"C",system:"Behavioral Health",topic:"Lithium monitoring — serum TSH (hypothyroidism)",action:"RESCORE_WITH_SHIFT",orig:148},
  {q:152,ans:"D",system:"Behavioral Health",topic:"Chlorpromazine — low-potency antipsychotic, anticholinergic effects",action:"RESCORE_WITH_SHIFT",orig:149},
  {q:153,ans:"A",system:"Behavioral Health",topic:"Alcohol withdrawal — benzodiazepines (lorazepam)",action:"RESCORE_WITH_SHIFT",orig:150},
  {q:154,ans:"B",system:"Behavioral Health",topic:"MDMA intoxication — serotonin/dopamine/NE release, hyponatremia",action:"RESCORE_WITH_SHIFT",orig:151},
  {q:155,ans:"D",system:"Behavioral Health",topic:"Delirium tremens — lorazepam (alcohol withdrawal)",action:"RESCORE_WITH_SHIFT",orig:152},
  {q:156,ans:"B",system:"Behavioral Health",topic:"MDMA — serotonin syndrome risk, hyponatremia",action:"RESCORE_WITH_SHIFT",orig:153},
  {q:157,ans:"E",system:"Renal & Urinary System",topic:"Acute tubular necrosis — muddy brown casts, basement membrane denudation",action:"RESCORE_WITH_SHIFT",orig:154},
  {q:158,ans:"B",system:"Renal & Urinary System",topic:"Salicylate toxicity — mixed acid-base disorder",action:"RESCORE_WITH_SHIFT",orig:155},
  {q:159,ans:"A",system:"Renal & Urinary System",topic:"Hypokalemia — increased H+/K+ antiporter in alpha-intercalated cells",action:"RESCORE_WITH_SHIFT",orig:156},
  {q:160,ans:"A",system:"Renal & Urinary System",topic:"Prerenal AKI — volume depletion",action:"RESCORE_WITH_SHIFT",orig:157},
  {q:161,ans:"E",system:"Renal & Urinary System",topic:"Poststreptococcal GN — granular IgG/IgM/C3, subepithelial humps",action:"RESCORE_WITH_SHIFT",orig:158},
  {q:162,ans:"A",system:"Renal & Urinary System",topic:"Diabetic nephropathy — hyaline arteriolosclerosis",action:"RESCORE_WITH_SHIFT",orig:159},
  {q:163,ans:"E",system:"Renal & Urinary System",topic:"Struvite kidney stones — magnesium ammonium phosphate (urease bacteria)",action:"RESCORE_WITH_SHIFT",orig:160},
  {q:164,ans:"E",system:"Renal & Urinary System",topic:"Staphylococcus saprophyticus — novobiocin-resistant UTI",action:"RESCORE_WITH_SHIFT",orig:161},
  {q:165,ans:"C",system:"Renal & Urinary System",topic:"Stress incontinence — urethral hypermobility, weakened pelvic floor",action:"RESCORE_WITH_SHIFT",orig:162},
  {q:166,ans:"D",system:"Renal & Urinary System",topic:"Thiazide diuretics — distal convoluted tubule, Na+/Cl- cotransporter",action:"RESCORE_WITH_SHIFT",orig:163},
  {q:167,ans:"B",system:"Pregnancy & Reproductive System",topic:"Carbamazepine teratogenicity — neural tube defects",action:"RESCORE_WITH_SHIFT",orig:164},
  {q:168,ans:"F",system:"Pregnancy & Reproductive System",topic:"Congenital toxoplasmosis — chorioretinitis, hydrocephalus, calcifications",action:"RESCORE_WITH_SHIFT",orig:165},
  {q:169,ans:"C",system:"Pregnancy & Reproductive System",topic:"Meckel diverticulum — patent vitelline duct",action:"RESCORE_WITH_SHIFT",orig:166},
  {q:170,ans:"D",system:"Pregnancy & Reproductive System",topic:"Developmental milestones — 2-year-old",action:"RESCORE_WITH_SHIFT",orig:167},
  {q:171,ans:"E",system:"Pregnancy & Reproductive System",topic:"PCOS — endometrial carcinoma from unopposed estrogen",action:"RESCORE_WITH_SHIFT",orig:168},
  {q:172,ans:"F",system:"Pregnancy & Reproductive System",topic:"Menopause — increased FSH (most reliable marker)",action:"RESCORE_WITH_SHIFT",orig:169},
  {q:173,ans:"C",system:"Pregnancy & Reproductive System",topic:"Turner syndrome — bicuspid aortic valve → aortic stenosis",action:"RESCORE_WITH_SHIFT",orig:170},
  {q:174,ans:"A",system:"Pregnancy & Reproductive System",topic:"Aromatase deficiency — ambiguous genitalia in 46,XX females",action:"RESCORE_WITH_SHIFT",orig:171},
  {q:175,ans:"B",system:"Pregnancy & Reproductive System",topic:"Adenomyosis — endometrial tissue within myometrium",action:"RESCORE_WITH_SHIFT",orig:172},
  {q:176,ans:"F",system:"Pregnancy & Reproductive System",topic:"PID — ectopic pregnancy risk",action:"RESCORE_WITH_SHIFT",orig:173},
  {q:177,ans:"E",system:"Pregnancy & Reproductive System",topic:"Communicating hydrocele — patent processus vaginalis",action:"RESCORE_WITH_SHIFT",orig:174},
  {q:178,ans:"D",system:"Respiratory System",topic:"Post-influenza lung — type II pneumocyte proliferation",action:"RESCORE_WITH_SHIFT",orig:175},
  {q:179,ans:"C",system:"Respiratory System",topic:"Opioid overdose — acute respiratory acidosis",action:"RESCORE_WITH_SHIFT",orig:176},
  {q:180,ans:"E",system:"Respiratory System",topic:"Severe asthma — physical exam findings",action:"RESCORE_WITH_SHIFT",orig:177},
  {q:181,ans:"E",system:"Respiratory System",topic:"Squamous cell carcinoma of lung — cigarette smoking, central cavitation",action:"RESCORE_WITH_SHIFT",orig:178},
  {q:182,ans:"C",system:"Respiratory System",topic:"Emphysema — obstructive spirometry, reduced DLCO",action:"RESCORE_WITH_SHIFT",orig:179},
  {q:183,ans:"B",system:"Respiratory System",topic:"Cystic fibrosis — congenital bilateral absence of vas deferens",action:"RESCORE_WITH_SHIFT",orig:180},
  {q:184,ans:"D",system:"Respiratory System",topic:"Sarcoidosis — elevated CD4+ T cells in BAL",action:"RESCORE_WITH_SHIFT",orig:181},
  {q:185,ans:"G",system:"Respiratory System",topic:"Pulmonary fibrosis — excess collagen deposition (amiodarone)",action:"RESCORE_WITH_SHIFT",orig:182},
  {q:186,ans:"A",system:"Respiratory System",topic:"Pulmonary embolism — DVT from raloxifene (SERM)",action:"RESCORE_WITH_SHIFT",orig:183},
  {q:187,ans:"B",system:"Respiratory System",topic:"Severe asthma — omalizumab downregulates FcεRI",action:"RESCORE_WITH_SHIFT",orig:184},
  {q:188,ans:"C",system:"Biostatistics & Public Health Science",topic:"Relative risk — appropriate measure for cohort studies",action:"RESCORE_WITH_SHIFT",orig:185},
  {q:189,ans:"A",system:"Biostatistics & Public Health Science",topic:"Lowering diagnostic cutoff — increases sensitivity and NPV",action:"RESCORE_WITH_SHIFT",orig:186},
  {q:190,ans:"D",system:"Biostatistics & Public Health Science",topic:"Precision — interrater reliability (reproducibility)",action:"RESCORE_WITH_SHIFT",orig:187},
  {q:191,ans:"A",system:"Biostatistics & Public Health Science",topic:"Case-control study — retrospective, starts with outcome",action:"RESCORE_WITH_SHIFT",orig:188},
  {q:192,ans:"D",system:"Biostatistics & Public Health Science",topic:"Confidence intervals — p-value relationship",action:"RESCORE_WITH_SHIFT",orig:189},
  {q:193,ans:"C",system:"Biostatistics & Public Health Science",topic:"Statistical power — decrease type II error rate",action:"RESCORE_WITH_SHIFT",orig:190},
  {q:194,ans:"C",system:"Biostatistics & Public Health Science",topic:"Confounding",action:"AWARD_AUTO_CREDIT",orig:null},
  {q:195,ans:"B",system:"Biostatistics & Public Health Science",topic:"Bladder cancer — transitional cell carcinoma, cigarette smoking",action:"RESCORE_WITH_SHIFT",orig:191},
  {q:196,ans:"B",system:"Biostatistics & Public Health Science",topic:"Demographic transition — childhood immunization",action:"RESCORE_WITH_SHIFT",orig:192},
  {q:197,ans:"E",system:"Biostatistics & Public Health Science",topic:"Pediatric informed consent — address parental concern empathetically",action:"RESCORE_WITH_SHIFT",orig:193},
  {q:198,ans:"C",system:"Biostatistics & Public Health Science",topic:"Patient confidentiality — HIPAA, no disclosure without consent",action:"RESCORE_WITH_SHIFT",orig:194},
  {q:199,ans:"E",system:"Biostatistics & Public Health Science",topic:"Language barriers — remote medical interpreter",action:"RESCORE_WITH_SHIFT",orig:195},
  {q:200,ans:"F",system:"Biostatistics & Public Health Science",topic:"Shaken baby syndrome — subdural hematoma (bridging vein tear)",action:"RESCORE_WITH_SHIFT",orig:196},
]

// Authoritative answer key from the fixed AMBOSS 200Q JSON (question_number 1–200).
// Keys match the question numbers students see on the physical exam and bubble sheet.
const PDF_200Q: Record<string, {a: string, s: string, t: string}> = {
  "1":{a:"E",s:"Biochemistry & Genetics",t:"X-linked recessive inheritance"},
  "2":{a:"B",s:"Biochemistry & Genetics",t:"Pleiotropy — PKU"},
  "3":{a:"F",s:"Biochemistry & Genetics",t:"Prader-Willi syndrome"},
  "4":{a:"C",s:"Biochemistry & Genetics",t:"Fragile X syndrome"},
  "5":{a:"E",s:"Biochemistry & Genetics",t:"Primary ciliary dyskinesia"},
  "6":{a:"A",s:"Biochemistry & Genetics",t:"Edwards syndrome (Trisomy 18)"},
  "7":{a:"B",s:"Biochemistry & Genetics",t:"Thiamine (B1) deficiency"},
  "8":{a:"A",s:"Biochemistry & Genetics",t:"Pompe disease"},
  "9":{a:"E",s:"Biochemistry & Genetics",t:"Carcinoid syndrome"},
  "10":{a:"A",s:"Biochemistry & Genetics",t:"Fluoroquinolone mechanism"},
  "11":{a:"F",s:"Biochemistry & Genetics",t:"Gaucher disease"},
  "12":{a:"E",s:"Biochemistry & Genetics",t:"Ehlers-Danlos syndrome"},
  "13":{a:"B",s:"Biochemistry & Genetics",t:"Insulin metabolic effects"},
  "14":{a:"E",s:"Biochemistry & Genetics",t:"Vitamin B12"},
  "15":{a:"A",s:"Biochemistry & Genetics",t:"Cystic fibrosis — vitamin deficiency"},
  "16":{a:"G",s:"Biochemistry & Genetics",t:"Pyridoxine (B6)"},
  "17":{a:"B",s:"General Pathology",t:"Apoptosis — intrinsic pathway"},
  "18":{a:"A",s:"General Pathology",t:"Coagulative necrosis"},
  "19":{a:"C",s:"General Pathology",t:"Methemoglobinemia"},
  "20":{a:"F",s:"General Pathology",t:"Alpha-1-antitrypsin deficiency"},
  "21":{a:"E",s:"General Pathology",t:"Wound healing — myofibroblasts"},
  "22":{a:"E",s:"General Pathology",t:"Vascular permeability"},
  "23":{a:"B",s:"General Pathology",t:"Tuberculosis — granulomas"},
  "24":{a:"D",s:"General Pathology",t:"IL-2 / Aldesleukin"},
  "25":{a:"D",s:"General Pathology",t:"TNM staging"},
  "26":{a:"D",s:"General Pathology",t:"Lynch syndrome"},
  "27":{a:"C",s:"General Pathology",t:"Li-Fraumeni syndrome"},
  "28":{a:"F",s:"General Pathology",t:"Prostate cancer"},
  "29":{a:"A",s:"General Pathology",t:"Urge incontinence"},
  "30":{a:"A",s:"General Pharmacology",t:"Desmopressin"},
  "31":{a:"E",s:"General Pharmacology",t:"Competitive antagonism"},
  "32":{a:"B",s:"General Pharmacology",t:"Enzyme kinetics"},
  "33":{a:"B",s:"General Pharmacology",t:"Bioavailability"},
  "34":{a:"A",s:"General Pharmacology",t:"Phase I clinical trials"},
  "35":{a:"F",s:"General Pharmacology",t:"CYP450 inducers"},
  "36":{a:"F",s:"General Pharmacology",t:"CYP450 — drug interactions"},
  "37":{a:"C",s:"Microbiology",t:"Chronic granulomatous disease"},
  "38":{a:"E",s:"Microbiology",t:"S. pneumoniae virulence"},
  "39":{a:"E",s:"Microbiology",t:"Gram-negative sepsis"},
  "40":{a:"A",s:"Microbiology",t:"Pertussis toxin"},
  "41":{a:"D",s:"Microbiology",t:"Mycoplasma pneumoniae"},
  "42":{a:"F",s:"Microbiology",t:"Bacillus cereus"},
  "43":{a:"A",s:"Microbiology",t:"Syphilis treatment"},
  "44":{a:"C",s:"Microbiology",t:"Hepatitis C"},
  "45":{a:"B",s:"Microbiology",t:"HIV entry — CCR5 coreceptor"},
  "46":{a:"D",s:"Microbiology",t:"PCP prophylaxis"},
  "47":{a:"D",s:"Microbiology",t:"Zidovudine (AZT)"},
  "48":{a:"A",s:"Microbiology",t:"Entamoeba histolytica"},
  "49":{a:"C",s:"Microbiology",t:"Plasmodium falciparum"},
  "50":{a:"F",s:"Microbiology",t:"Cryptococcus neoformans"},
  "51":{a:"F",s:"Microbiology",t:"Trichomonas vaginalis"},
  "52":{a:"C",s:"Immune System",t:"Aging immune system"},
  "53":{a:"C",s:"Immune System",t:"Chronic mucocutaneous candidiasis"},
  "54":{a:"D",s:"Immune System",t:"Goodpasture syndrome"},
  "55":{a:"C",s:"Immune System",t:"Acute renal transplant rejection"},
  "56":{a:"C",s:"Immune System",t:"Tetanus vaccine"},
  "57":{a:"B",s:"Immune System",t:"Leukocyte adhesion deficiency (LAD)"},
  "58":{a:"A",s:"Immune System",t:"Terminal complement deficiency"},
  "59":{a:"D",s:"Immune System",t:"EBV and lymphoma"},
  "60":{a:"D",s:"Immune System",t:"Cyclosporine"},
  "61":{a:"E",s:"Blood & Lymphoreticular System",t:"Sideroblastic anemia"},
  "62":{a:"C",s:"Blood & Lymphoreticular System",t:"Lead poisoning"},
  "63":{a:"E",s:"Blood & Lymphoreticular System",t:"Hemolytic disease of newborn"},
  "64":{a:"C",s:"Blood & Lymphoreticular System",t:"Alpha-thalassemia minor"},
  "65":{a:"C",s:"Blood & Lymphoreticular System",t:"Sickle cell anemia"},
  "66":{a:"E",s:"Blood & Lymphoreticular System",t:"Polycythemia vera"},
  "67":{a:"A",s:"Blood & Lymphoreticular System",t:"AML-M3 (APL)"},
  "68":{a:"A",s:"Blood & Lymphoreticular System",t:"Multiple myeloma"},
  "69":{a:"A",s:"Blood & Lymphoreticular System",t:"Hemolytic uremic syndrome (HUS)"},
  "70":{a:"C",s:"Blood & Lymphoreticular System",t:"Hemophilia"},
  "71":{a:"C",s:"Blood & Lymphoreticular System",t:"Warfarin mechanism"},
  "72":{a:"F",s:"Blood & Lymphoreticular System",t:"Testicular cancer spread"},
  "73":{a:"E",s:"Blood & Lymphoreticular System",t:"Heme & Onc — additional concept"},
  "74":{a:"C",s:"Cardiovascular System",t:"Beta-1 antagonism in CHF"},
  "75":{a:"C",s:"Cardiovascular System",t:"Persistent truncus arteriosus"},
  "76":{a:"A",s:"Cardiovascular System",t:"Tetralogy of Fallot"},
  "77":{a:"F",s:"Cardiovascular System",t:"Cor pulmonale"},
  "78":{a:"D",s:"Cardiovascular System",t:"Hypovolemic shock"},
  "79":{a:"D",s:"Cardiovascular System",t:"Restrictive cardiomyopathy"},
  "80":{a:"B",s:"Cardiovascular System",t:"Mitral stenosis"},
  "81":{a:"C",s:"Cardiovascular System",t:"S3 heart sound"},
  "82":{a:"B",s:"Cardiovascular System",t:"Dressler syndrome"},
  "83":{a:"C",s:"Cardiovascular System",t:"Infective endocarditis — renal involvement"},
  "84":{a:"E",s:"Cardiovascular System",t:"Wolff-Parkinson-White (WPW)"},
  "85":{a:"B",s:"Cardiovascular System",t:"Polyarteritis nodosa"},
  "86":{a:"A",s:"Cardiovascular System",t:"Familial hyperchylomicronemia"},
  "87":{a:"B",s:"Cardiovascular System",t:"Polyarteritis nodosa"},
  "88":{a:"B",s:"Cardiovascular System",t:"Familial hyperchylomicronemia — acute pancreatitis"},
  "89":{a:"A",s:"Cardiovascular System",t:"Statin adverse effects — myopathy"},
  "90":{a:"A",s:"Endocrine System",t:"Graves disease"},
  "91":{a:"B",s:"Endocrine System",t:"Pregnancy thyroid changes"},
  "92":{a:"A",s:"Endocrine System",t:"Secondary hyperparathyroidism"},
  "93":{a:"B",s:"Endocrine System",t:"Central diabetes insipidus"},
  "94":{a:"A",s:"Endocrine System",t:"Neuroblastoma"},
  "95":{a:"D",s:"Endocrine System",t:"Addison disease"},
  "96":{a:"F",s:"Endocrine System",t:"Cushing syndrome"},
  "97":{a:"B",s:"Endocrine System",t:"Type 2 diabetes — islet pathology"},
  "98":{a:"A",s:"Endocrine System",t:"Glucagonoma"},
  "99":{a:"F",s:"Endocrine System",t:"Hemochromatosis"},
  "100":{a:"D",s:"Endocrine System",t:"MEN 2"},
  "101":{a:"A",s:"Endocrine System",t:"TSH receptor signaling"},
  "102":{a:"C",s:"Endocrine System",t:"Sulfonylureas"},
  "103":{a:"B",s:"Endocrine System",t:"Chagas disease — GI manifestations"},
  "104":{a:"D",s:"Gastrointestinal System",t:"Chagas esophageal dysmotility"},
  "105":{a:"D",s:"Gastrointestinal System",t:"Bulimia nervosa — GI complication"},
  "106":{a:"E",s:"Gastrointestinal System",t:"Peptic ulcer disease"},
  "107":{a:"E",s:"Gastrointestinal System",t:"Whipple disease"},
  "108":{a:"G",s:"Gastrointestinal System",t:"Hirschsprung disease"},
  "109":{a:"B",s:"Gastrointestinal System",t:"Crohn disease"},
  "110":{a:"D",s:"Gastrointestinal System",t:"Portal hypertension"},
  "111":{a:"E",s:"Gastrointestinal System",t:"Hepatitis B serology"},
  "112":{a:"E",s:"Gastrointestinal System",t:"Acute cholecystitis"},
  "113":{a:"E",s:"Gastrointestinal System",t:"Pancreatic cancer"},
  "114":{a:"A",s:"Skin & Musculoskeletal System",t:"Congenital rubella"},
  "115":{a:"D",s:"Skin & Musculoskeletal System",t:"Tinea versicolor"},
  "116":{a:"E",s:"Skin & Musculoskeletal System",t:"Pemphigus vulgaris"},
  "117":{a:"C",s:"Skin & Musculoskeletal System",t:"Neuroleptic malignant syndrome (NMS)"},
  "118":{a:"C",s:"Skin & Musculoskeletal System",t:"Myasthenia gravis"},
  "119":{a:"D",s:"Skin & Musculoskeletal System",t:"Serotonin syndrome"},
  "120":{a:"B",s:"Skin & Musculoskeletal System",t:"Muscle contraction"},
  "121":{a:"E",s:"Skin & Musculoskeletal System",t:"SLE antibodies"},
  "122":{a:"F",s:"Skin & Musculoskeletal System",t:"CREST syndrome"},
  "123":{a:"C",s:"Skin & Musculoskeletal System",t:"Rheumatoid arthritis"},
  "124":{a:"E",s:"Skin & Musculoskeletal System",t:"Reactive arthritis"},
  "125":{a:"F",s:"Skin & Musculoskeletal System",t:"Dermatomyositis"},
  "126":{a:"E",s:"Skin & Musculoskeletal System",t:"Paget disease of bone"},
  "127":{a:"A",s:"Skin & Musculoskeletal System",t:"Meyer loop — visual pathway"},
  "128":{a:"E",s:"Nervous System & Special Senses",t:"Horner syndrome"},
  "129":{a:"E",s:"Nervous System & Special Senses",t:"CN III palsy"},
  "130":{a:"C",s:"Nervous System & Special Senses",t:"Facial nerve (CN VII) anatomy"},
  "131":{a:"D",s:"Nervous System & Special Senses",t:"Vitamin B12 neurologic disease"},
  "132":{a:"E",s:"Nervous System & Special Senses",t:"Huntington disease"},
  "133":{a:"F",s:"Nervous System & Special Senses",t:"Epidural hematoma"},
  "134":{a:"E",s:"Nervous System & Special Senses",t:"ACA stroke"},
  "135":{a:"H",s:"Nervous System & Special Senses",t:"Multiple sclerosis"},
  "136":{a:"C",s:"Nervous System & Special Senses",t:"Neurofibromatosis type 2"},
  "137":{a:"C",s:"Nervous System & Special Senses",t:"Anterior cord syndrome"},
  "138":{a:"B",s:"Nervous System & Special Senses",t:"Narcolepsy"},
  "139":{a:"E",s:"Nervous System & Special Senses",t:"Poliomyelitis"},
  "140":{a:"B",s:"Nervous System & Special Senses",t:"Guillain-Barre syndrome"},
  "141":{a:"C",s:"Nervous System & Special Senses",t:"Alzheimer disease"},
  "142":{a:"C",s:"Nervous System & Special Senses",t:"Radial nerve palsy"},
  "143":{a:"E",s:"Nervous System & Special Senses",t:"Organophosphate poisoning"},
  "144":{a:"B",s:"Nervous System & Special Senses",t:"Behavioral change stages — contemplation"},
  "145":{a:"C",s:"Nervous System & Special Senses",t:"Borderline personality disorder"},
  "146":{a:"E",s:"Behavioral Health",t:"Schizophreniform disorder"},
  "147":{a:"E",s:"Behavioral Health",t:"Major depressive disorder"},
  "148":{a:"C",s:"Behavioral Health",t:"Antisocial personality disorder"},
  "149":{a:"A",s:"Behavioral Health",t:"Anorexia nervosa"},
  "150":{a:"B",s:"Behavioral Health",t:"Bipolar disorder"},
  "151":{a:"C",s:"Behavioral Health",t:"Lithium monitoring"},
  "152":{a:"D",s:"Behavioral Health",t:"Chlorpromazine"},
  "153":{a:"A",s:"Behavioral Health",t:"Alcohol withdrawal"},
  "154":{a:"B",s:"Behavioral Health",t:"MDMA intoxication"},
  "155":{a:"D",s:"Behavioral Health",t:"Delirium tremens"},
  "156":{a:"B",s:"Behavioral Health",t:"MDMA complications"},
  "157":{a:"E",s:"Renal & Urinary System",t:"Acute tubular necrosis (ATN)"},
  "158":{a:"B",s:"Renal & Urinary System",t:"Salicylate toxicity"},
  "159":{a:"A",s:"Renal & Urinary System",t:"Hypokalemia"},
  "160":{a:"A",s:"Renal & Urinary System",t:"Prerenal AKI"},
  "161":{a:"E",s:"Renal & Urinary System",t:"Poststreptococcal GN (PSGN)"},
  "162":{a:"A",s:"Renal & Urinary System",t:"Diabetic nephropathy"},
  "163":{a:"E",s:"Renal & Urinary System",t:"Struvite kidney stones"},
  "164":{a:"E",s:"Renal & Urinary System",t:"Staphylococcus saprophyticus"},
  "165":{a:"C",s:"Renal & Urinary System",t:"Stress incontinence"},
  "166":{a:"D",s:"Renal & Urinary System",t:"Thiazide diuretics"},
  "167":{a:"B",s:"Pregnancy & Reproductive System",t:"Carbamazepine teratogenicity"},
  "168":{a:"F",s:"Pregnancy & Reproductive System",t:"Congenital toxoplasmosis"},
  "169":{a:"C",s:"Pregnancy & Reproductive System",t:"Meckel diverticulum"},
  "170":{a:"D",s:"Pregnancy & Reproductive System",t:"Developmental milestones — 2-year-old"},
  "171":{a:"E",s:"Pregnancy & Reproductive System",t:"PCOS"},
  "172":{a:"F",s:"Pregnancy & Reproductive System",t:"Menopause"},
  "173":{a:"C",s:"Pregnancy & Reproductive System",t:"Turner syndrome"},
  "174":{a:"A",s:"Pregnancy & Reproductive System",t:"Aromatase deficiency"},
  "175":{a:"B",s:"Pregnancy & Reproductive System",t:"Adenomyosis"},
  "176":{a:"F",s:"Pregnancy & Reproductive System",t:"PID"},
  "177":{a:"E",s:"Pregnancy & Reproductive System",t:"Communicating hydrocele"},
  "178":{a:"D",s:"Respiratory System",t:"Post-influenza lung repair"},
  "179":{a:"C",s:"Respiratory System",t:"Opioid overdose"},
  "180":{a:"E",s:"Respiratory System",t:"Severe asthma — physical findings"},
  "181":{a:"E",s:"Respiratory System",t:"Squamous cell carcinoma of lung"},
  "182":{a:"C",s:"Respiratory System",t:"Emphysema"},
  "183":{a:"B",s:"Respiratory System",t:"Cystic fibrosis — male infertility"},
  "184":{a:"D",s:"Respiratory System",t:"Sarcoidosis"},
  "185":{a:"G",s:"Respiratory System",t:"Pulmonary fibrosis"},
  "186":{a:"A",s:"Respiratory System",t:"Pulmonary embolism"},
  "187":{a:"B",s:"Respiratory System",t:"Omalizumab for asthma"},
  "188":{a:"C",s:"Biostatistics & Public Health Science",t:"Relative risk"},
  "189":{a:"A",s:"Biostatistics & Public Health Science",t:"Increased negative predictive value"},
  "190":{a:"D",s:"Biostatistics & Public Health Science",t:"Precision"},
  "191":{a:"A",s:"Biostatistics & Public Health Science",t:"Case-control study"},
  "192":{a:"D",s:"Biostatistics & Public Health Science",t:"P-value"},
  "193":{a:"C",s:"Biostatistics & Public Health Science",t:"Type II error rate (beta)"},
  "194":{a:"C",s:"Biostatistics & Public Health Science",t:"Confounding"},
  "195":{a:"B",s:"Biostatistics & Public Health Science",t:"Bladder cancer — risk factors"},
  "196":{a:"B",s:"Biostatistics & Public Health Science",t:"Demographic transition"},
  "197":{a:"E",s:"Biostatistics & Public Health Science",t:"Core ethical principles"},
  "198":{a:"C",s:"Biostatistics & Public Health Science",t:"Withholding information from patients"},
  "199":{a:"E",s:"Biostatistics & Public Health Science",t:"Patient communication — interpreter"},
  "200":{a:"F",s:"Biostatistics & Public Health Science",t:"Child abuse — mandatory reporting"},
}

export function is200QExam(examName: string): boolean {
  return examName.toLowerCase().includes('200q') || examName.toLowerCase().includes('stepup 200')
}

export interface QuestionDetail {
  qNum: number
  studentAnswer: string
  correctAnswer: string
  correct: boolean
  system?: string
  topic?: string
  discipline?: string
}

// Grades all 200 questions using the authoritative answer key.
// allAnswers keys are the question numbers students saw on the exam (1–200).
export function gradeWith200QKey(
  allAnswers: Record<string, string>
): QuestionDetail[] {
  const results: QuestionDetail[] = []
  for (let q = 1; q <= 200; q++) {
    const qStr = String(q)
    const entry = PDF_200Q[qStr]
    if (!entry) continue
    const studentAnswer = String(allAnswers[qStr] ?? '').toUpperCase().trim()
    const correct = !!studentAnswer && studentAnswer === entry.a
    results.push({
      qNum: q,
      studentAnswer: studentAnswer || '—',
      correctAnswer: entry.a,
      correct,
      system: entry.s,
      topic: entry.t,
      discipline: entry.s,
    })
  }
  return results
}
